### ISSUE TITLE
Line 44 mpnn_charge_prediction.bash

### ISSUE THREAD

**Issue by Ombiyani** [SimonEnsemble/mpn_charges#4]
I was trying to run  ./mpnn_charge_prediction.bash mof_name.cif. I kept getting the following issue. I think it has something to do with how docker is mounting the julia file. 
![capture 3](https://user-images.githubusercontent.com/93807310/182960755-945bf6d8-f5c2-4a16-88c5-21ea528c31fe.PNG)
I ran the script line by line and found that I would get the error message on line 44 of the bash file .
![Capture2](https://user-images.githubusercontent.com/93807310/182960488-df7c1fcf-e88b-4ad0-ab25-d9985e22946f.PNG)
Please let me know if you have a solution. Thanks!

Edit: I think the issue has to do with the drive mapping option the old docker engine used.  I am using docker desktop version 4.10.1. The issue is most likely that the script can't navigate the container drive paths and my host drive paths because they haven't been mapped.

**Comment by SimonEnsemble** [comment]
hoping @aliraza-ece can help you, as he assembled this Docker image.

**Comment by aliraza-ece** [comment]
from the cli, it looks like you have docker installed and the script is able to start a container and copy files to it, however, **`exec` command is not working correctly**. i don't have access to a window machine right now to debug but you can try this: 
`docker exec -it mpnn_charge_prediction_container sh`
`docker exec -it mpnn_charge_prediction_container /julia/julia-1.4.2/bin/julia assign_mpnn_charges.jl "$1"`
$1 is input MOF's name. 
let me know how it goes.

**Comment by Ombiyani** [comment]
Sorry for the late response, I have managed to resolve the issue. Thanks for your input.
